const $=s=>document.querySelector(s);let DATA=null;
function calc(t,p){if(!t)return {text:'No lecture data yet.',kind:'neutral',n:0};if(p/t<.75){let n=Math.ceil((.75*t-p)/.25);return {text:`Attend next ${n} class${n===1?'':'es'} to reach 75%`,kind:'need',n}}let n=Math.max(0,Math.floor(p/.75-t));return n?{text:`Can miss ${n} class${n===1?'':'es'} and stay ≥75%`,kind:'bunk',n}:{text:'Attend the next class to protect 75%',kind:'need',n:1}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(d){DATA=d;let subs=d.subjects||[],T=subs.reduce((a,s)=>a+(+s.total||0),0),P=subs.reduce((a,s)=>a+(+s.present||0),0),A=subs.reduce((a,s)=>a+(+s.absent||0),0);$('#overall').textContent=Number.isFinite(+d.erpOverall)?(+d.erpOverall).toFixed(2)+'%':(T?(100*P/T).toFixed(1)+'%':'—');$('#present').textContent=P||'—';$('#absent').textContent=A||'—';$('#total').textContent=T||'—';$('#last').textContent=d.syncedAt?new Date(d.syncedAt).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'Never';$('#student').textContent=d.student||'ABES student';$('#cards').innerHTML='';subs.forEach((s,i)=>{let pct=s.total?100*s.present/s.total:0,cl=pct>=75?'good':pct>=70?'warn':'bad',label=pct>=75?'Safe':pct>=70?'Close':'Below 75%',a=calc(+s.total||0,+s.present||0);let e=document.createElement('article');e.className='card';e.innerHTML=`<div class="top"><div><h3>${esc(s.name||s.code||'Subject')}</h3><div class="code">${esc(s.code||'')}</div></div><div class="pctbox"><span class="badge ${cl}">${label}</span><div class="pct ${cl}">${pct.toFixed(1)}%</div></div></div><div class="stats"><span><b>${s.present||0}</b> Present</span><span><b>${s.absent||0}</b> Absent</span><span><b>${s.total||0}</b> Total</span></div><div class="bar"><div class="fill ${cl}" style="width:${Math.min(100,pct)}%"></div></div><div class="advice ${a.kind}">${a.text}</div>${s.history?.length?`<button class="view" data-i="${i}">View date-wise history (${s.history.length} entries)</button>`:''}`;$('#cards').appendChild(e)});document.querySelectorAll('.view').forEach(b=>b.onclick=()=>showHistory(+b.dataset.i));}
function showHistory(i){let s=DATA.subjects[i];$('#htitle').textContent=s.name||s.code;$('#hmeta').textContent=`${s.present}/${s.total} present • ${(100*s.present/s.total).toFixed(1)}%`;$('#hbody').innerHTML=`<table class="hist"><thead><tr><th>Date</th><th>Lectures</th><th>Status</th></tr></thead><tbody>${(s.history||[]).map(r=>`<tr><td>${esc(r.date||'')}</td><td>${r.lectures||1}</td><td class="${String(r.status).toUpperCase().startsWith('P')?'good':'bad'}"><b>${esc(r.status||'')}</b></td></tr>`).join('')}</tbody></table>`;$('#history').showModal()}
$('#close').onclick=()=>$('#history').close();
chrome.storage.local.get('abesAttendance',x=>{if(x.abesAttendance){render(x.abesAttendance);$('#msg').textContent='Showing saved attendance. Open ERP Attendance and Sync Now for latest data.';$('#msg').className='msg ok'}});
$('#sync').onclick=async()=>{let [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.url?.startsWith('https://erp.abes.ac.in/ERP/Dashboard/Student/Attendance/')){fail('Open My Attendance in ABES ERP first.');return}$('#sync').disabled=true;$('#sync').textContent='Syncing…';try{let [{result}]=await chrome.scripting.executeScript({target:{tabId:tab.id},world:'MAIN',func:scrapeERP});if(!result?.subjects?.length)throw new Error(result?.error||'Attendance rows were not found.');result.syncedAt=Date.now();await chrome.storage.local.set({abesAttendance:result});render(result);$('#msg').textContent=`Synced ${result.subjects.length} subjects${result.historyCount?` + ${result.historyCount} attendance records`:''}.`;$('#msg').className='msg ok'}catch(e){fail(e.message||String(e))}finally{$('#sync').disabled=false;$('#sync').textContent='Sync Now'}};
function fail(t){$('#msg').textContent=t;$('#msg').className='msg err'}
async function scrapeERP(){try{const clean=s=>String(s??'').replace(/\s+/g,' ').trim(),num=s=>{let m=clean(s).match(/\d+(?:\.\d+)?/);return m?+m[0]:0},pick=(o,keys)=>{for(const k of keys)if(o&&o[k]!=null&&o[k]!=='')return o[k];return ''},parseD=j=>{let x=j?.d??j;if(typeof x==='string'){try{x=JSON.parse(x)}catch{}}return Array.isArray(x)?x:(x?.Table||x?.data||x?.Data||[])};
let text=document.body.innerText,erpOverallMatch=text.match(/Attendance\s*%\s*:\s*(\d+(?:\.\d+)?)/i),erpOverall=erpOverallMatch?+erpOverallMatch[1]:null,student=(text.match(/(?:Welcome|Student Name)\s*[:\-]?\s*([^\n]+)/i)||[])[1]||'',rows=[...document.querySelectorAll('table tr')],subjects=[];
for(const tr of rows){let cells=[...tr.querySelectorAll('td')].map(x=>clean(x.innerText));if(cells.length<5)continue;let ci=cells.findIndex(x=>/^\d{2}[A-Z]{2}\d{3}$/.test(x));if(ci<0)continue;let code=cells[ci],name=cells[ci+1]||code,total=num(cells[ci+2]),present=num(cells[ci+3]),absent=num(cells[ci+4]);if(total&&total>=present&&Math.abs(total-present-absent)<=2&&!subjects.some(s=>s.code===code))subjects.push({code,name,total,present,absent,history:[]})}
let sel=document.querySelector('select');let sem=sel?.value||'CS03';if(!/^CS\d+/i.test(sem)){let op=sel?.selectedOptions?.[0];sem=op?.value||'CS03'}
// Event endpoint can provide cleaner subject totals and subject IDs; keep both when available.
let eventIds={};
try{let r=await fetch(location.pathname+'/getEventAtt',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json; charset=UTF-8'},body:JSON.stringify({StudentDashBAL:{semid:sem,mode:'MyEventAttendance'}})}),arr=parseD(await r.json());for(const o of arr){let subj=clean(pick(o,['subject','Subject','SubjectName','subjectname'])),m=subj.match(/(\d{2}[A-Z]{2}\d{3})\s*[~\-:]?\s*(.*)/),code=clean(pick(o,['SubjectCode','subjectcode']))||m?.[1]||'',name=(m?.[2]||subj||code).trim(),total=num(pick(o,['TotalLecture','Total','total','TotLec'])),present=num(pick(o,['Present','present','P'])),absent=num(pick(o,['Absent','absent','A'])),sid=clean(pick(o,['SubjectID','SubjectId','subjectID','subjectId','subjectid','SubID','subid','Subject_Id','subject_id']));if(code&&/^SU\d+$/i.test(sid))eventIds[code]=sid;let s=subjects.find(x=>x.code===code);if(s){if(name&&name!==code)s.name=name;if(total){s.total=total;s.present=present;s.absent=absent}}else if(code&&total)subjects.push({code,name,total,present,absent,history:[]})}}catch(_){}
// Use each subject id already embedded in the page's action controls to fetch date-wise history.
let ids={...eventIds};for(const el of document.querySelectorAll('[onclick],a[href],button')){let raw=(el.getAttribute('onclick')||'')+' '+(el.getAttribute('href')||'');let code=(raw.match(/\d{2}[A-Z]{2}\d{3}/)||[])[0],sid=(raw.match(/SU\d+/i)||[])[0];if(code&&sid)ids[code]=sid}
// Fallback: associate SU ids with rows when both appear in row HTML.
for(const tr of rows){let h=tr.outerHTML,code=(h.match(/\d{2}[A-Z]{2}\d{3}/)||[])[0],sid=(h.match(/SU\d+/i)||[])[0];if(code&&sid)ids[code]=sid}
let historyCount=0;for(const s of subjects){let sid=ids[s.code];if(!sid)continue;try{let r=await fetch(location.pathname+'/getSubjectAtt',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json; charset=UTF-8'},body:JSON.stringify({StudentDashBAL:{semid:sem,subjectid:sid,mode:'MySubjectAttendance'}})}),arr=parseD(await r.json());s.history=arr.map(o=>({date:clean(pick(o,['AttDate','attdate','Date','date'])),lectures:num(pick(o,['NoOfLecture','NoOfLectures','Lecture','lecture','NoLecture']))||1,status:clean(pick(o,['Attendance','attendance','Status','status','AttStatus']))})).filter(x=>x.date&&x.status);historyCount+=s.history.length}catch(_){}}
return {student:clean(student)||'ABES student',subjects,historyCount,erpOverall};}catch(e){return {error:e.message,subjects:[]}}}

const clearBtn=document.querySelector('#clearData');if(clearBtn)clearBtn.onclick=async()=>{if(confirm('Clear attendance saved by this extension on this browser?')){await chrome.storage.local.remove('abesAttendance');location.reload();}};
